### ISSUE TITLE
Scripts are blocked

### ISSUE THREAD

**Issue by Elardzhi** [zhgabor/adminer-table-filter#5]
Hi
I have these 2 errors:

Content Security Policy: The page’s settings blocked the loading of a resource at http://code.jquery.com/jquery-3.1.1.slim.min.js (“script-src”).

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

**Comment by zhgabor** [comment]
Use https for jquery. I will update repo

**Comment by Elardzhi** [comment]
That was a Content Security Policy issue. Sent a Pull request #6

**Comment by zhgabor** [comment]
Thanks for the update
